import core from '@actions/core';

/**
 * Creates inline PR review comments for verified issues.
 * If an inline comment fails due to diff hunk alignment, it falls back gracefully without breaking execution.
 * @param {Object} octokit - The Octokit client.
 * @param {Object} context - The GitHub Action context.
 * @param {string} commitSha - The target commit SHA.
 * @param {Array} issues - Array of verified issues.
 */
export async function postInlineReviewComments(octokit, context, commitSha, issues) {
  const { owner, repo, number: pull_number } = context.issue;

  console.log(`Posting ${issues.length} inline review comments on PR #${pull_number}...`);

  for (const issue of issues) {
    const commentBody = `
### 🤖 PR State Bug Hunter Warning 🛡️

**Bug Type:** \`${issue.ruleId}\`
**Severity:** ${issue.severity === 'HIGH' ? '🔴 HIGH' : issue.severity === 'MEDIUM' ? '🟡 MEDIUM' : '🟢 LOW'}

**Analysis:**
${issue.explanation}

${issue.proposedFix ? `**Proposed Fix:**\n${issue.proposedFix}` : ''}

_Review conducted by PR State Bug Hunter AI. Please verify logical context before applying changes._
`;

    try {
      await octokit.rest.pulls.createReviewComment({
        owner,
        repo,
        pull_number,
        body: commentBody,
        commit_id: commitSha,
        path: issue.filePath,
        line: issue.line,
        side: 'RIGHT'
      });
      console.log(`Successfully posted inline comment on ${issue.filePath}:${issue.line}`);
    } catch (err) {
      core.warning(`Could not post inline review comment on ${issue.filePath}:${issue.line}: ${err.message}. Inline comment added to summary report instead.`);
    }
  }
}

/**
 * Generates and posts a gorgeous markdown summary comment at the top of the PR.
 * @param {Object} octokit - The Octokit client.
 * @param {Object} context - The GitHub Action context.
 * @param {number} filesScannedCount - Number of files scanned.
 * @param {number} astWarningsCount - Number of AST warnings found.
 * @param {Array} verifiedIssues - Array of AI verified issues.
 */
export async function postPrSummaryComment(octokit, context, filesScannedCount, astWarningsCount, verifiedIssues) {
  const { owner, repo, number: pull_number } = context.issue;

  console.log(`Posting comprehensive PR Summary Comment...`);

  // Build the gorgeous markdown dashboard
  let summaryBody = `## 🛡️ PR State Bug Hunter Report 🚀

An AI-powered static & semantic review has been completed for this pull request. We scanned code structures for asynchronous state leaks, React hook race conditions, memory leaks, and communication protocol hazards.

### 📊 Scan Summary Dashboard
| Metric | Result |
| :--- | :--- |
| 📂 **Files Scanned** | \`${filesScannedCount}\` |
| 🔍 **AST Warning Spots Found** | \`${astWarningsCount}\` |
| 🤖 **AI-Verified Logical Bugs** | \`${verifiedIssues.length}\` |
| 🛡️ **Action Status** | ${verifiedIssues.length > 0 ? '⚠️ Review Required' : '✅ Ready to Merge'} |

---

`;

  if (verifiedIssues.length === 0) {
    summaryBody += `### ✅ No State Bugs or Race Conditions Detected!
Our static analysis and AI models audited your changes and found no issues relating to React hook lifecycle leaks, stale state asynchronous updates, stream framing, or event listener cleanup. Excellent work! 🌟
`;
  } else {
    summaryBody += `### 🔴 Critical & Moderate Issues Requiring Attention
Below is the breakdown of the **${verifiedIssues.length}** issues detected by our hybrid analysis system.

`;

    // Group issues by file
    const issuesByFile = {};
    for (const issue of verifiedIssues) {
      if (!issuesByFile[issue.filePath]) {
        issuesByFile[issue.filePath] = [];
      }
      issuesByFile[issue.filePath].push(issue);
    }

    for (const [filePath, fileIssues] of Object.entries(issuesByFile)) {
      summaryBody += `#### 📄 File: \`${filePath}\`

<details open>
<summary><b>Click to toggle details for this file (${fileIssues.length} issues)</b></summary>
<br/>

`;

      for (const issue of fileIssues) {
        summaryBody += `
##### ⚠️ Line ${issue.line}: \`${issue.ruleId}\` (${issue.severity === 'HIGH' ? '🔴 HIGH' : issue.severity === 'MEDIUM' ? '🟡 MEDIUM' : '🟢 LOW'})

* **Explanation:** 
  ${issue.explanation}

${issue.proposedFix ? `* **Proposed Fix:**\n${issue.proposedFix}` : ''}

---
`;
      }

      summaryBody += `</details>\n\n`;
    }
  }

  summaryBody += `
---
_Report generated by **[PR State Bug Hunter](https://github.com/marketplace/actions/pr-state-bug-hunter)**. Add high-performance AI state auditing to your CI/CD pipelines._
`;

  try {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: pull_number,
      body: summaryBody
    });
    console.log("Successfully posted the gorgeous PR summary comment!");
  } catch (err) {
    core.setFailed(`Failed to post summary comment on PR: ${err.message}`);
  }
}

/**
 * Smartly commits proposed AI fixes directly to the PR branch via Octokit createOrUpdateFileContents.
 * @param {Object} octokit - The Octokit client.
 * @param {Object} context - The GitHub Action context.
 * @param {string} branchName - Target PR branch name.
 * @param {string} filePath - Path of the file to fix.
 * @param {string} updatedContent - The fully patched file contents.
 * @param {number|string} lineNum - The line number fixed, or 'all'.
 */
export async function commitFixToPrBranch(octokit, context, branchName, filePath, updatedContent, lineNum) {
  const { owner, repo } = context.issue;

  console.log(`Committing auto-fix changes back to branch "${branchName}" for file "${filePath}"...`);

  try {
    // 1. Fetch file meta-information to obtain its current blob SHA
    let fileSha;
    try {
      const { data } = await octokit.rest.repos.getContent({
        owner,
        repo,
        path: filePath,
        ref: branchName
      });
      fileSha = data.sha;
    } catch (err) {
      console.log(`[Octokit Warning]: File might be newly created or missing: ${err.message}`);
    }

    // 2. Commit the patched content
    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: filePath,
      message: `🤖 [PR Bug Hunter] Auto-fix state/async bug on line ${lineNum}`,
      content: Buffer.from(updatedContent).toString('base64'),
      sha: fileSha,
      branch: branchName
    });

    console.log(`✅ [Octokit] Successfully committed fix to ${filePath} on branch ${branchName}!`);
  } catch (error) {
    console.error(`❌ [Octokit Error] Could not commit fix to branch ${branchName}: ${error.message}`);
    throw error;
  }
}

